version: '3.8'

services:
  swiftwordpress:
    build: .
    command: sh -c "yarn install && yarn dev"
    ports:
      - "8002:8002"
    volumes:
      - .:/usr/src/swiftwordpress
      - /usr/src/swiftwordpress/node_modules