services:
  wordpress:
    depends_on:
      - db
    image: wordpress:${WP_VERSION}
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wp:/var/www/html
    labels:
      com.docker.compose.project: ${PROJECT_NAME}

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    labels:
      com.docker.compose.project: ${PROJECT_NAME}

  wpcli:
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wp:/var/www/html
    depends_on:
      - db
      - wordpress
    labels:
      com.docker.compose.project: ${PROJECT_NAME}

volumes:
  db:
    labels:
      com.docker.compose.project: ${PROJECT_NAME}
  wp:
    labels:
      com.docker.compose.project: ${PROJECT_NAME}
