services:
  wordpress:
    image: wordpress:${WP_VERSION}
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WP_HOST: ${WP_HOST}
      WP_PORT: ${WP_PORT}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      WP_LANGUAGE: ${WP_LANGUAGE}
      PROJECT_NAME: ${PROJECT_NAME}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - wordpress_data:/var/www/html
      - ./wait-for-db.sh:/usr/local/bin/wait-for-db.sh
      - ./wpcli_setup.sh:/usr/local/bin/wpcli_setup.sh
      - ./wp-cli.phar:/usr/local/bin/wp
    entrypoint: >
      /bin/sh -c "
        if [ ! -f /var/www/html/.entrypoint_done ]; then
          apt-get update &&
          apt-get install -y default-mysql-client curl &&
          chmod +x /usr/local/bin/wp &&
          chmod +x /usr/local/bin/wait-for-db.sh &&
          chmod +x /usr/local/bin/wpcli_setup.sh &&
          /usr/local/bin/wait-for-db.sh &&
          /usr/local/bin/wpcli_setup.sh &&
          touch /var/www/html/.entrypoint_done
        fi &&
        exec /usr/local/bin/docker-entrypoint.sh apache2-foreground
      "
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
