version: '3.8'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "%{MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: "%{MYSQL_USER}"
      MYSQL_PASSWORD: "%{MYSQL_PASSWORD}"
    ports:
      - "3306:3306"

  wordpress_db_init:
    image: mysql:latest
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: "%{MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: "%{MYSQL_USER}"
      MYSQL_PASSWORD: "%{MYSQL_PASSWORD}"
    command: ["bash", "-c", "sleep 10 && mysql -hdb -u root -p%{MYSQL_ROOT_PASSWORD} -e 'CREATE DATABASE IF NOT EXISTS wordpress;'"]

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80" # Change port as needed
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "%{MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "%{MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data:
